// Imports for user GUI programs run by the native playground (wasmi).
//
// Generated by tools/gen_bindings.py from the ABI table; do not edit.
// gpu / clipboard forward to the host modules (guest byte ranges are copied
// into host memory first); the rest go to the sandbox in guest.rs.

#![allow(clippy::too_many_arguments, unused_variables)]

use wasmi::{Caller, Linker};
use crate::guest::{Guest, guest_bytes};

pub fn link(linker: &mut Linker<Guest>) -> Result<(), wasmi::Error> {
    linker.func_wrap("gpu", "surface_format", |mut c: Caller<'_, Guest>| -> i64 { let _ = &mut c;  crate::gpu::surface_format() })?;
    linker.func_wrap("gpu", "create_shader", |mut c: Caller<'_, Guest>, src_ptr: i64, src_len: i64| -> i64 { let _ = &mut c; let src_ptr_buf = guest_bytes(&c, src_ptr, src_len); crate::gpu::create_shader(src_ptr_buf.as_ptr() as i64, src_ptr_buf.len() as i64) })?;
    linker.func_wrap("gpu", "create_render_pipeline", |mut c: Caller<'_, Guest>, shader: i64, vs_ptr: i64, vs_len: i64, fs_ptr: i64, fs_len: i64, format: i64, blend: i64| -> i64 { let _ = &mut c; let vs_ptr_buf = guest_bytes(&c, vs_ptr, vs_len); let fs_ptr_buf = guest_bytes(&c, fs_ptr, fs_len); crate::gpu::create_render_pipeline(shader, vs_ptr_buf.as_ptr() as i64, vs_ptr_buf.len() as i64, fs_ptr_buf.as_ptr() as i64, fs_ptr_buf.len() as i64, format, blend) })?;
    linker.func_wrap("gpu", "create_buffer", |mut c: Caller<'_, Guest>, size: i64, usage: i64| -> i64 { let _ = &mut c;  crate::gpu::create_buffer(size, usage) })?;
    linker.func_wrap("gpu", "write_buffer", |mut c: Caller<'_, Guest>, buffer: i64, offset: i64, ptr: i64, len: i64| { let _ = &mut c; let ptr_buf = guest_bytes(&c, ptr, len); crate::gpu::write_buffer(buffer, offset, ptr_buf.as_ptr() as i64, ptr_buf.len() as i64) })?;
    linker.func_wrap("gpu", "create_texture", |mut c: Caller<'_, Guest>, width: i64, height: i64, format: i64, usage: i64| -> i64 { let _ = &mut c;  crate::gpu::create_texture(width, height, format, usage) })?;
    linker.func_wrap("gpu", "write_texture", |mut c: Caller<'_, Guest>, texture: i64, x: i64, y: i64, width: i64, height: i64, ptr: i64, len: i64, bytes_per_row: i64| { let _ = &mut c; let ptr_buf = guest_bytes(&c, ptr, len); crate::gpu::write_texture(texture, x, y, width, height, ptr_buf.as_ptr() as i64, ptr_buf.len() as i64, bytes_per_row) })?;
    linker.func_wrap("gpu", "create_sampler", |mut c: Caller<'_, Guest>, filter: i64| -> i64 { let _ = &mut c;  crate::gpu::create_sampler(filter) })?;
    linker.func_wrap("gpu", "bind_begin", |mut c: Caller<'_, Guest>| { let _ = &mut c;  crate::gpu::bind_begin() })?;
    linker.func_wrap("gpu", "bind_buffer", |mut c: Caller<'_, Guest>, binding: i64, buffer: i64| { let _ = &mut c;  crate::gpu::bind_buffer(binding, buffer) })?;
    linker.func_wrap("gpu", "bind_texture", |mut c: Caller<'_, Guest>, binding: i64, texture: i64| { let _ = &mut c;  crate::gpu::bind_texture(binding, texture) })?;
    linker.func_wrap("gpu", "bind_sampler", |mut c: Caller<'_, Guest>, binding: i64, sampler: i64| { let _ = &mut c;  crate::gpu::bind_sampler(binding, sampler) })?;
    linker.func_wrap("gpu", "bind_create", |mut c: Caller<'_, Guest>, pipeline: i64, group: i64| -> i64 { let _ = &mut c;  crate::gpu::bind_create(pipeline, group) })?;
    linker.func_wrap("gpu", "frame_begin", |mut c: Caller<'_, Guest>| -> i64 { let _ = &mut c;  crate::gpu::frame_begin() })?;
    linker.func_wrap("gpu", "target_width", |mut c: Caller<'_, Guest>, target: i64| -> i64 { let _ = &mut c;  crate::gpu::target_width(target) })?;
    linker.func_wrap("gpu", "target_height", |mut c: Caller<'_, Guest>, target: i64| -> i64 { let _ = &mut c;  crate::gpu::target_height(target) })?;
    linker.func_wrap("gpu", "pass_begin", |mut c: Caller<'_, Guest>, target: i64, load: i64, r: f64, g: f64, b: f64, a: f64| -> i64 { let _ = &mut c;  crate::gpu::pass_begin(target, load, r, g, b, a) })?;
    linker.func_wrap("gpu", "pass_pipeline", |mut c: Caller<'_, Guest>, pass: i64, pipeline: i64| { let _ = &mut c;  crate::gpu::pass_pipeline(pass, pipeline) })?;
    linker.func_wrap("gpu", "pass_bind", |mut c: Caller<'_, Guest>, pass: i64, index: i64, group: i64| { let _ = &mut c;  crate::gpu::pass_bind(pass, index, group) })?;
    linker.func_wrap("gpu", "pass_scissor", |mut c: Caller<'_, Guest>, pass: i64, x: i64, y: i64, width: i64, height: i64| { let _ = &mut c;  crate::gpu::pass_scissor(pass, x, y, width, height) })?;
    linker.func_wrap("gpu", "pass_draw", |mut c: Caller<'_, Guest>, pass: i64, vertices: i64, instances: i64, first_vertex: i64, first_instance: i64| { let _ = &mut c;  crate::gpu::pass_draw(pass, vertices, instances, first_vertex, first_instance) })?;
    linker.func_wrap("gpu", "pass_end", |mut c: Caller<'_, Guest>, pass: i64| { let _ = &mut c;  crate::gpu::pass_end(pass) })?;
    linker.func_wrap("gpu", "frame_submit", |mut c: Caller<'_, Guest>| { let _ = &mut c;  crate::gpu::frame_submit() })?;
    linker.func_wrap("gpu", "release", |mut c: Caller<'_, Guest>, handle: i64| { let _ = &mut c;  crate::gpu::release(handle) })?;
    linker.func_wrap("gpu", "external_texture", |mut c: Caller<'_, Guest>, context_id: i64| -> i64 { 0 })?;
    linker.func_wrap("clipboard", "clipboard_write", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| { let _ = &mut c; let ptr_buf = guest_bytes(&c, ptr, len); crate::clipboard::clipboard_write(ptr_buf.as_ptr() as i64, ptr_buf.len() as i64) })?;
    linker.func_wrap("sys", "abi_version", |mut c: Caller<'_, Guest>| -> i64 { crate::guest::sys_abi_version(&mut c) })?;
    linker.func_wrap("sys", "run", |mut c: Caller<'_, Guest>| { crate::guest::sys_run(&mut c) })?;
    linker.func_wrap("sys", "request_frame", |mut c: Caller<'_, Guest>| { crate::guest::sys_request_frame(&mut c) })?;
    linker.func_wrap("sys", "request_frame_after", |mut c: Caller<'_, Guest>, ms: f64| { crate::guest::sys_request_frame_after(&mut c, ms) })?;
    linker.func_wrap("sys", "now_ms", |mut c: Caller<'_, Guest>| -> f64 { crate::guest::sys_now_ms(&mut c) })?;
    linker.func_wrap("sys", "log", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| { crate::guest::sys_log(&mut c, ptr, len) })?;
    linker.func_wrap("sys", "event_len", |mut c: Caller<'_, Guest>| -> i64 { crate::guest::sys_event_len(&mut c) })?;
    linker.func_wrap("sys", "event_read", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| -> i64 { crate::guest::sys_event_read(&mut c, ptr, len) })?;
    linker.func_wrap("sys", "platform", |mut c: Caller<'_, Guest>| -> i64 { crate::guest::sys_platform(&mut c) })?;
    linker.func_wrap("sys", "set_cursor", |mut c: Caller<'_, Guest>, kind: i64| { crate::guest::sys_set_cursor(&mut c, kind) })?;
    linker.func_wrap("sys", "set_title", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| { crate::guest::sys_set_title(&mut c, ptr, len) })?;
    linker.func_wrap("sys", "open_url", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| { crate::guest::sys_open_url(&mut c, ptr, len) })?;
    linker.func_wrap("sys", "asset_len", |mut c: Caller<'_, Guest>, name_ptr: i64, name_len: i64| -> i64 { crate::guest::sys_asset_len(&mut c, name_ptr, name_len) })?;
    linker.func_wrap("sys", "asset_read", |mut c: Caller<'_, Guest>, name_ptr: i64, name_len: i64, dst_ptr: i64, dst_len: i64| -> i64 { crate::guest::sys_asset_read(&mut c, name_ptr, name_len, dst_ptr, dst_len) })?;
    linker.func_wrap("sys", "exit", |mut c: Caller<'_, Guest>, code: i64| { crate::guest::sys_exit(&mut c, code) })?;
    linker.func_wrap("sys", "launch_len", |mut c: Caller<'_, Guest>| -> i64 { crate::guest::sys_launch_len(&mut c) })?;
    linker.func_wrap("sys", "launch_read", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| -> i64 { crate::guest::sys_launch_read(&mut c, ptr, len) })?;
    linker.func_wrap("sys", "set_location", |mut c: Caller<'_, Guest>, ptr: i64, len: i64| { crate::guest::sys_set_location(&mut c, ptr, len) })?;
    linker.func_wrap("text_input", "ime_begin", |mut c: Caller<'_, Guest>, x: f64, y: f64, w: f64, h: f64| { crate::guest::text_input_ime_begin(&mut c, x, y, w, h) })?;
    linker.func_wrap("text_input", "ime_update", |mut c: Caller<'_, Guest>, x: f64, y: f64, w: f64, h: f64| { crate::guest::text_input_ime_update(&mut c, x, y, w, h) })?;
    linker.func_wrap("text_input", "ime_end", |mut c: Caller<'_, Guest>| { crate::guest::text_input_ime_end(&mut c) })?;
    linker.func_wrap("a11y", "a11y_active", |mut c: Caller<'_, Guest>| -> i64 { crate::guest::a11y_a11y_active(&mut c) })?;
    linker.func_wrap("a11y", "a11y_begin", |mut c: Caller<'_, Guest>| { crate::guest::a11y_a11y_begin(&mut c) })?;
    linker.func_wrap("a11y", "a11y_node", |mut c: Caller<'_, Guest>, id: i64, parent: i64, role: i64, x: f64, y: f64, w: f64, h: f64, flags: i64, label_ptr: i64, label_len: i64| { crate::guest::a11y_a11y_node(&mut c, id, parent, role, x, y, w, h, flags, label_ptr, label_len) })?;
    linker.func_wrap("a11y", "a11y_value", |mut c: Caller<'_, Guest>, id: i64, ptr: i64, len: i64| { crate::guest::a11y_a11y_value(&mut c, id, ptr, len) })?;
    linker.func_wrap("a11y", "a11y_commit", |mut c: Caller<'_, Guest>, focus_id: i64| { crate::guest::a11y_a11y_commit(&mut c, focus_id) })?;
    linker.func_wrap("storage", "storage_len", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64| -> i64 { crate::guest::storage_storage_len(&mut c, key_ptr, key_len) })?;
    linker.func_wrap("storage", "storage_read", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64, dst_ptr: i64, dst_len: i64| -> i64 { crate::guest::storage_storage_read(&mut c, key_ptr, key_len, dst_ptr, dst_len) })?;
    linker.func_wrap("storage", "storage_write", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64, ptr: i64, len: i64| { crate::guest::storage_storage_write(&mut c, key_ptr, key_len, ptr, len) })?;
    linker.func_wrap("storage", "storage_remove", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64| { crate::guest::storage_storage_remove(&mut c, key_ptr, key_len) })?;
    linker.func_wrap("storage", "secret_len", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64| -> i64 { crate::guest::storage_secret_len(&mut c, key_ptr, key_len) })?;
    linker.func_wrap("storage", "secret_read", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64, dst_ptr: i64, dst_len: i64| -> i64 { crate::guest::storage_secret_read(&mut c, key_ptr, key_len, dst_ptr, dst_len) })?;
    linker.func_wrap("storage", "secret_write", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64, ptr: i64, len: i64| { crate::guest::storage_secret_write(&mut c, key_ptr, key_len, ptr, len) })?;
    linker.func_wrap("storage", "secret_remove", |mut c: Caller<'_, Guest>, key_ptr: i64, key_len: i64| { crate::guest::storage_secret_remove(&mut c, key_ptr, key_len) })?;
    linker.func_wrap("net", "http_begin", |mut c: Caller<'_, Guest>, method_ptr: i64, method_len: i64, url_ptr: i64, url_len: i64| -> i64 { crate::guest::net_http_begin(&mut c, method_ptr, method_len, url_ptr, url_len) })?;
    linker.func_wrap("net", "http_header", |mut c: Caller<'_, Guest>, id: i64, name_ptr: i64, name_len: i64, value_ptr: i64, value_len: i64| { crate::guest::net_http_header(&mut c, id, name_ptr, name_len, value_ptr, value_len) })?;
    linker.func_wrap("net", "http_send", |mut c: Caller<'_, Guest>, id: i64, body_ptr: i64, body_len: i64| { crate::guest::net_http_send(&mut c, id, body_ptr, body_len) })?;
    linker.func_wrap("net", "http_cancel", |mut c: Caller<'_, Guest>, id: i64| { crate::guest::net_http_cancel(&mut c, id) })?;
    linker.func_wrap("file", "file_open", |mut c: Caller<'_, Guest>, kind: i64| -> i64 { crate::guest::file_file_open(&mut c, kind) })?;
    linker.func_wrap("file", "file_save", |mut c: Caller<'_, Guest>, name_ptr: i64, name_len: i64, ptr: i64, len: i64| -> i64 { crate::guest::file_file_save(&mut c, name_ptr, name_len, ptr, len) })?;
    Ok(())
}
