#!/usr/bin/env python3
"""Generate ceangal/src/emoji_data.almd: which code points are emoji by
default (Emoji_Presentation) and which can become emoji
(Extended_Pictographic), from Unicode's emoji-data.txt.

Usage:  python3 tools/gen_emoji.py <dir with emoji-data.txt>
(https://www.unicode.org/Public/16.0.0/ucd/emoji/)
"""
import os
import sys

from packing import FORMAT, literal, pack

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def ranges(path, prop):
    cps = set()
    for line in open(path, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        r, p = [s.strip() for s in line.split(";")]
        if p != prop:
            continue
        a, _, b = r.partition("..")
        cps.update(range(int(a, 16), int(b or a, 16) + 1))
    out = []
    for cp in sorted(cps):
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def packed(name, rs, doc):
    return f"// {doc}\npub let {name} =\n{literal(pack(rs))}\n"


def render(pres, pict):
    return ("// Generated by tools/gen_emoji.py from Unicode 16.0 emoji-data.txt. Do not edit.\n"
            f"// Ranges of code points: {FORMAT}.\n\n"
            + packed("PRESENTATION", pres, "Shown as emoji by default (Emoji_Presentation).") + "\n"
            + packed("PICTOGRAPHIC", pict, "Can be shown as emoji: with U+FE0F, or inside a sequence (Extended_Pictographic)."))


def main():
    src = os.path.join(sys.argv[1] if len(sys.argv) > 1 else ".", "emoji-data.txt")
    pres = ranges(src, "Emoji_Presentation")
    pict = ranges(src, "Extended_Pictographic")
    text = render(pres, pict)
    dst = os.path.join(ROOT, "ceangal", "src", "emoji_data.almd")
    open(dst, "w").write(text)
    print(f"{os.path.relpath(dst, ROOT)}: {len(pres)} + {len(pict)} ranges")


if __name__ == "__main__":
    main()
