#!/usr/bin/env python3
"""docs/api/: the API reference, generated from the Almide sources.

For each module an app imports, the file's leading comment is the intro, and
every `pub fn`, every type, and every constant with a comment is listed with
its signature and the comment right above it. `// ── Name ──` comments start
sections. CI regenerates and fails when docs/api/ differs (`--check`).

  python3 tools/gen_api_docs.py          write docs/api/
  python3 tools/gen_api_docs.py --check  exit 1 if docs/api/ is stale
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs/api"

# (import path, source, one-line summary for the index)
MODULES = [
    ("ceangal", "ceangal/src/mod.almd", "the app: run, focus, keyboard, viewport, clipboard"),
    ("ceangal.view", "ceangal/src/view.almd", "views and modifiers: text, col, row, styles, events, accessibility"),
    ("ceangal.widgets", "ceangal/src/widgets.almd", "standard controls: buttons, checkboxes, switches, sliders, dialogs…"),
    ("ceangal.editor", "ceangal/src/editor.almd", "a multi-line text editor view"),
    ("ceangal.storage", "ceangal/src/storage.almd", "saved values and secrets"),
    ("ceangal.http", "ceangal/src/http.almd", "HTTP requests"),
    ("ceangal.text", "ceangal/src/text.almd", "fonts: shaping, measuring and drawing text"),
    ("ceangal.syntax", "ceangal/src/syntax.almd", "Almide syntax highlighting"),
    ("snaidhm", "snaidhm/src/mod.almd", "the renderer: colours, frames, shapes, images"),
    ("snaidhm.vector", "snaidhm/src/vector.almd", "vector paths: fill and stroke"),
    ("snaidhm.font", "snaidhm/src/font.almd", "TrueType parsing and glyph rasterising"),
]

SECTION = re.compile(r"^//\s*──\s*(.+?)\s*──")
ITEM = re.compile(r"^(pub (?:effect )?fn|type|let)\s+([A-Za-z_][A-Za-z0-9_]*)")


def comment_text(lines):
    out = []
    for l in lines:
        t = l[2:]
        out.append(t[1:] if t.startswith(" ") else t)
    return "\n".join(out).strip("\n")


def signature(lines, i):
    """The item's declaration up to its `=` (fns, lets) or the whole type."""
    kind = ITEM.match(lines[i]).group(1)
    text, depth, j = "", 0, i
    while j < len(lines):
        line = lines[j]
        for k, ch in enumerate(line):
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            elif ch == "=" and depth == 0 and kind != "type" and line[k - 1:k] not in ("=", "!", "<", ">") and line[k + 1:k + 2] not in ("=", ">"):
                return (text + line[:k]).rstrip()
        text += line + "\n"
        j += 1
        if kind == "type" and depth == 0:
            # a variant type continues on lines starting with `|`
            if j < len(lines) and lines[j].lstrip().startswith("|"):
                continue
            return text.rstrip()
    return text.rstrip()


def module_doc(name, src, summary):
    lines = (ROOT / src).read_text().splitlines()
    # the file's leading comment
    intro, i = [], 0
    while i < len(lines) and lines[i].startswith("//"):
        intro.append(lines[i])
        i += 1
    md = [f"# `{name}`", "", f"<!-- Generated by tools/gen_api_docs.py from {src}; do not edit. -->", ""]
    md += [f"_{summary[0].upper() + summary[1:]}._", ""]
    if intro:
        md += [comment_text(intro), ""]
    md += [f"```almide\nimport {name}\n```", ""]
    pending, entries = [], 0
    group = []  # undocumented items in a row: one block of signatures

    def flush():
        if group:
            md.extend(["```almide", "\n".join(group), "```", ""])
            group.clear()

    for j in range(i, len(lines)):
        line = lines[j]
        sec = SECTION.match(line)
        if sec:
            flush()
            md.extend([f"## {sec.group(1)}", ""])
            pending = []
            continue
        if line.startswith("//"):
            pending.append(line)
            continue
        m = ITEM.match(line)
        if m:
            kind, ident = m.groups()
            doc = comment_text(pending)
            pending = []
            if kind == "let" and not doc:
                continue
            if kind == "type" and ident[0].islower():
                continue
            entries += 1
            sig = signature(lines, j)
            if not doc and "\n" not in sig:
                group.append(sig)
                continue
            flush()
            md.extend([f"### `{ident}`", "", "```almide", sig, "```", ""])
            if doc:
                md.extend([doc, ""])
            continue
        pending = []
    flush()
    return "\n".join(md).rstrip() + "\n", entries


def generate():
    files = {}
    index = ["# API reference", "", "<!-- Generated by tools/gen_api_docs.py; do not edit. -->", "",
             "Generated from the sources' comments: `python3 tools/gen_api_docs.py` after",
             "changing a public function, type or its comment (CI checks it is current).",
             "The guides are in [../guide](../guide/README.md).", "",
             "| module | | entries |", "|---|---|---|"]
    for name, src, summary in MODULES:
        text, n = module_doc(name, src, summary)
        files[f"{name}.md"] = text
        index.append(f"| [`{name}`]({name}.md) | {summary} | {n} |")
    files["README.md"] = "\n".join(index) + "\n"
    return files


def main():
    files = generate()
    if "--check" in sys.argv:
        stale = [f for f, t in files.items() if not (OUT / f).exists() or (OUT / f).read_text() != t]
        extra = [p.name for p in OUT.glob("*.md") if p.name not in files] if OUT.exists() else []
        if stale or extra:
            print("docs/api is out of date (run python3 tools/gen_api_docs.py):", ", ".join(stale + extra))
            sys.exit(1)
        print(f"docs/api is current ({len(files)} files)")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    for p in OUT.glob("*.md"):
        if p.name not in files:
            p.unlink()
    for f, t in files.items():
        (OUT / f).write_text(t)
    print(f"wrote {len(files)} files in docs/api")


main()
