#!/usr/bin/env python3
"""Generate ceangal/src/linebreak_data.almd (line break classes, UAX #14)
and tests/linebreak/cases.txt (the expected break opportunities) from
Unicode 16.0's LineBreak.txt, EastAsianWidth.txt and LineBreakTest.txt.

Usage:  python3 tools/gen_linebreak.py <dir with the three .txt files>
(https://www.unicode.org/Public/16.0.0/ucd/ and ucd/auxiliary/)

ceangal.linebreak classifies a code point with `default_class` below
(CJK ideographs ID, Hangul syllables H2/H3, the emoji blocks ID, anything
else AL) unless the table says otherwise. The table covers the blocks in
BLOCKS. East Asian width comes from `east_asian` below and is not
stored. The tests keep the LineBreakTest.txt lines whose code points all
get their exact class and width this way.
"""
import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLASSES = ("BK CR LF NL SP ZW CM ZWJ WJ GL BA HY B2 BB CB CL CP EX IN IS NS OP QU SY PR PO NU AL HL ID EB EM RI "
           "H2 H3 JL JV JT").split()
BLOCKS = [(0x0000, 0x036F), (0x0370, 0x058F), (0x0590, 0x08FF), (0x0900, 0x0D7F), (0x0E00, 0x0EFF), (0x1100, 0x11FF),
          (0x1AB0, 0x1AFF), (0x1DC0, 0x1DFF), (0x2000, 0x20FF), (0x2E80, 0x2FFF), (0x3000, 0x33FF), (0xFB00, 0xFDFF),
          (0xFE00, 0xFE0F), (0xFE70, 0xFFFF), (0x1F000, 0x1FAFF), (0xE0000, 0xE01EF)]
DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_"


def load(path):
    d = {}
    for line in open(path, encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue
        r, c = [x.strip() for x in line.split(";")]
        a, b = r.split("..") if ".." in r else (r, r)
        for cp in range(int(a, 16), int(b, 16) + 1):
            d[cp] = c
    return d


def resolved(lb, cp):
    """LB1: the class the rules see (AI, SG, XX → AL; SA → CM or AL; CJ → NS).
    The aksara classes of LB28a become AL (that rule is not followed)."""
    c = lb.get(cp, "XX")
    if c in ("AI", "SG", "XX", "AK", "AP", "AS", "VI", "VF"):
        c = "AL"
    elif c == "SA":
        c = "CM" if unicodedata.category(chr(cp)) in ("Mn", "Mc") else "AL"
    elif c == "CJ":
        c = "NS"
    return c


def entry(lb, cp):
    c = resolved(lb, cp)
    gc = unicodedata.category(chr(cp))
    return (CLASSES.index(c), c == "QU" and gc == "Pi", c == "QU" and gc == "Pf")


def default_class(cp):
    if 0x3400 <= cp <= 0x4DBF or 0x4E00 <= cp <= 0x9FFF or 0xF900 <= cp <= 0xFAFF or 0x20000 <= cp <= 0x3FFFD:
        return (CLASSES.index("ID"), False, False)
    if 0xAC00 <= cp <= 0xD7A3:
        return (CLASSES.index("H2" if (cp - 0xAC00) % 28 == 0 else "H3"), False, False)
    if 0x1F000 <= cp <= 0x1FAFF or 0x1FC00 <= cp <= 0x1FFFD:
        return (CLASSES.index("ID"), False, False)
    return (CLASSES.index("AL"), False, False)


def east_asian(cp):
    """ceangal.linebreak's East Asian width (F, W or H), by ranges."""
    return (0x1100 <= cp <= 0x115F or 0x2E80 <= cp <= 0x303E or 0x3041 <= cp <= 0x33FF or 0x3400 <= cp <= 0x4DBF
            or 0x4E00 <= cp <= 0x9FFF or 0xA000 <= cp <= 0xA4CF or 0xAC00 <= cp <= 0xD7A3 or 0xF900 <= cp <= 0xFAFF
            or 0xFE30 <= cp <= 0xFE4F or 0xFF00 <= cp <= 0xFF60 or 0xFF61 <= cp <= 0xFFDC or 0xFFE0 <= cp <= 0xFFE6
            or 0x1F300 <= cp <= 0x1F64F or 0x1F900 <= cp <= 0x1F9FF or 0x20000 <= cp <= 0x3FFFD)


def varint(v):
    out = ""
    while v >= 32:
        out += DIGITS[32 + (v & 31)]
        v >>= 5
    return out + DIGITS[v]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "."
    lb = load(os.path.join(src, "LineBreak.txt"))
    eaw = load(os.path.join(src, "EastAsianWidth.txt"))
    rows = []
    for lo, hi in BLOCKS:
        for cp in range(lo, hi + 1):
            e = entry(lb, cp)
            if e == default_class(cp):
                continue
            if rows and rows[-1][1] == cp - 1 and rows[-1][2] == e:
                rows[-1][1] = cp
            else:
                rows.append([cp, cp, e])
    packed, prev = "", 0
    for a, b, (c, pi, pf) in rows:
        packed += varint(a - prev) + varint(b - a) + varint(c + 64 * pi + 128 * pf)
        prev = b
    body = "\n".join('  "%s" +' % packed[i:i + 96] for i in range(0, len(packed), 96)).rstrip(" +")
    text = f"""// Generated by tools/gen_linebreak.py from Unicode 16.0 LineBreak.txt. Do not edit.
//
// Line break classes (ceangal.linebreak's numbering) where they differ from
// the default for the code point: runs of (start − previous end, last −
// start, class + 64 if an initial quote + 128 if a final quote), each a
// little-endian base-32 number written with 64 digits (0-9 A-Z a-z - _):
// a digit of 32 or more has another after it.

pub let PACKED =
{body}
"""
    dst = os.path.join(ROOT, "ceangal", "src", "linebreak_data.almd")
    open(dst, "w").write(text)

    def covered(cp):
        in_block = any(lo <= cp <= hi for lo, hi in BLOCKS)
        exact = in_block or entry(lb, cp) == default_class(cp)
        ea = eaw.get(cp, "N") in ("F", "W", "H")
        # out: LB28a's aksara (and its dotted circle), LB30b's unassigned
        # pictographs, East Asian widths the ranges get wrong
        aksara = lb.get(cp) in ("AK", "AP", "AS", "VI", "VF") or cp == 0x25CC
        return exact and not aksara and ea == east_asian(cp) and not (unicodedata.category(chr(cp)) == "Cn" and cp >= 0x1F000)

    cases = []
    for line in open(os.path.join(src, "LineBreakTest.txt"), encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue
        toks = line.split()
        cps = [int(t, 16) for t in toks[1::2]]
        marks = toks[2::2]   # after each code point: ÷ (break) or × (no break)
        if all(covered(cp) for cp in cps):
            cases.append(" ".join("%X" % cp for cp in cps) + "\t" + "".join("1" if m == "÷" else "0" for m in marks[:-1]))
    os.makedirs(os.path.join(ROOT, "tests", "linebreak"), exist_ok=True)
    open(os.path.join(ROOT, "tests", "linebreak", "cases.txt"), "w").write("\n".join(cases) + "\n")
    print(f"linebreak_data.almd: {len(rows)} ranges, {len(packed)} chars; cases.txt: {len(cases)} lines")


if __name__ == "__main__":
    main()
