#!/usr/bin/env python3
"""Generate ceangal/src/indic_data.almd: the shaping category and matra side
of each character of the Indic scripts ceangal shapes (Devanagari, Bengali,
Gurmukhi, Gujarati, Tamil, Telugu, Kannada, Malayalam), from Unicode's IndicSyllabicCategory.txt and
IndicPositionalCategory.txt.

Usage:  python3 tools/gen_indic.py <dir with the two .txt files>
(https://www.unicode.org/Public/16.0.0/ucd/)
"""
import os
import sys

from packing import FORMAT, literal, pack

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOCKS = [(0x0900, 0x097F), (0x0980, 0x09FF), (0x0A00, 0x0A7F), (0x0A80, 0x0AFF), (0x0B80, 0x0BFF),
          (0x0C00, 0x0C7F), (0x0C80, 0x0CFF), (0x0D00, 0x0D7F)]

# ceangal.indic's categories
X, C, V, N, H, M, SM, ZWNJ, ZWJ, PH, REPHA = range(11)
SYLLABIC = {
    "Consonant": C, "Consonant_Dead": C, "Consonant_Placeholder": PH,
    "Vowel_Independent": V, "Vowel_Dependent": M, "Nukta": N, "Virama": H,
    "Bindu": SM, "Visarga": SM, "Cantillation_Mark": SM, "Syllable_Modifier": SM, "Gemination_Mark": SM,
    "Consonant_Preceding_Repha": REPHA,
}
# matra sides: 1 left (pre-base), 2 right, 3 top, 4 bottom, 5 split (decomposed first)
POSITIONAL = {
    "Left": 1, "Visual_Order_Left": 1,
    "Right": 2, "Top_And_Right": 2, "Bottom_And_Right": 2,
    "Top": 3, "Top_And_Bottom": 3, "Overstruck": 3,
    "Bottom": 4,
    "Left_And_Right": 5, "Top_And_Left": 5, "Top_And_Left_And_Right": 5, "Top_And_Bottom_And_Left": 5,
}


def read(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        cps, value = [s.strip() for s in line.split(";")]
        a, _, b = cps.partition("..")
        for cp in range(int(a, 16), int(b or a, 16) + 1):
            out[cp] = value
    return out


def render(rows):
    return f"""// Generated by tools/gen_indic.py from Unicode 16.0 IndicSyllabicCategory.txt
// and IndicPositionalCategory.txt. Do not edit.
//
// Devanagari, Bengali, Gurmukhi, Gujarati, Tamil, Telugu, Kannada and
// Malayalam: runs of characters with one category and matra side, as
// (first, last, category, side). Categories: 1 consonant, 2 independent
// vowel, 3 nukta, 4 virama, 5 matra, 6 syllable modifier, 9 placeholder,
// 10 repha (a reph of its own; everything else: 0). Matra sides: 1 left
// (pre-base), 2 right, 3 top, 4 bottom, 5 split. Written as {FORMAT}.

pub let PACKED =
{literal(pack(rows))}
"""


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "."
    syl = read(os.path.join(src, "IndicSyllabicCategory.txt"))
    pos = read(os.path.join(src, "IndicPositionalCategory.txt"))
    rows = []
    for lo, hi in BLOCKS:
        for cp in range(lo, hi + 1):
            cat = SYLLABIC.get(syl.get(cp, ""), X)
            side = POSITIONAL.get(pos.get(cp, ""), 0) if cat == M else 0
            if rows and rows[-1][1] == cp - 1 and rows[-1][2:] == [cat, side]:
                rows[-1][1] = cp
            else:
                rows.append([cp, cp, cat, side])
    rows = [r for r in rows if r[2] != X]
    text = render(rows)
    dst = os.path.join(ROOT, "ceangal", "src", "indic_data.almd")
    open(dst, "w").write(text)
    print(f"{os.path.relpath(dst, ROOT)}: {len(rows)} ranges")


if __name__ == "__main__":
    main()
