#!/usr/bin/env python3
"""Generate ceangal/src/arabic_data.almd: the joining type of each character
of the Arabic blocks, from Unicode's ArabicShaping.txt (characters it does
not list are transparent when they are marks or format characters, else
non-joining).

Usage:  python3 tools/gen_arabic.py <dir with ArabicShaping.txt>
(https://www.unicode.org/Public/16.0.0/ucd/)
"""
import os
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOCKS = [(0x0600, 0x06FF), (0x0750, 0x077F), (0x0860, 0x08FF), (0x200C, 0x200D)]
# ceangal.arabic's joining types
TYPES = {"U": 0, "L": 1, "R": 2, "D": 3, "T": 4, "C": 5}
# HarfBuzz's modifier combining marks (hamza above / below…)
MCM = {0x0654, 0x0655, 0x0658, 0x06DC, 0x06E3, 0x06E7, 0x06E8, 0x08CA, 0x08CB, 0x08CD, 0x08CE, 0x08CF, 0x08D3, 0x08F3}


def main():
    src = os.path.join(sys.argv[1] if len(sys.argv) > 1 else ".", "ArabicShaping.txt")
    listed = {}
    for line in open(src, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        listed[int(f[0], 16)] = f[2]
    rows = []
    for lo, hi in BLOCKS:
        for cp in range(lo, hi + 1):
            jt = listed.get(cp)
            if jt is None:
                jt = "T" if unicodedata.category(chr(cp)) in ("Mn", "Me", "Cf") else "U"
            t = TYPES[jt]
            if rows and rows[-1][1] == cp - 1 and rows[-1][2] == t:
                rows[-1][1] = cp
            else:
                rows.append([cp, cp, t])
    rows = [r for r in rows if r[2] != 0]
    # canonical combining classes of the marks (HarfBuzz orders marks by them)
    # as HarfBuzz orders Arabic marks: shadda first (its 33 becomes 27, and
    # 27-32 move up one); the hamza-like marks it moves to the front of their
    # run (MCM) get their class + 1 (221, 231: no character has those)
    def cls(cp):
        c = unicodedata.combining(chr(cp))
        c = 27 if c == 33 else c + 1 if 27 <= c <= 32 else c
        return c + 1 if cp in MCM else c
    ccc = []
    for lo, hi in BLOCKS[:3]:
        for cp in range(lo, hi + 1):
            if not unicodedata.combining(chr(cp)):
                continue
            if ccc and ccc[-1][1] == cp - 1 and ccc[-1][2] == cls(cp):
                ccc[-1][1] = cp
            else:
                ccc.append([cp, cp, cls(cp)])
    ccc_packed = "".join("%04X%04X%02X" % tuple(c) for c in ccc)
    ccc_body = "\n".join('  "%s" +' % ccc_packed[i:i + 96] for i in range(0, len(ccc_packed), 96)).rstrip(" +")
    packed = "".join("%04X%04X%X" % tuple(r) for r in rows)
    body = "\n".join('  "%s" +' % packed[i:i + 99] for i in range(0, len(packed), 99)).rstrip(" +")
    text = f"""// Generated by tools/gen_arabic.py from Unicode 16.0 ArabicShaping.txt. Do not edit.
//
// Joining types of the Arabic blocks (and ZWNJ / ZWJ): runs of 9 hex
// digits, first and last code point (4 each) and the type: 1 left-joining,
// 2 right-joining, 3 dual-joining, 4 transparent, 5 join-causing (anything
// else does not join).

pub let PACKED =
{body}

// Combining classes of the marks as HarfBuzz orders Arabic ones (shadda
// first; the hamza-like marks moved to the front of their run have their
// class + 1): runs of 10 hex digits, first and last code point (4 each)
// and the class (2).
pub let CCC =
{ccc_body}
"""
    dst = os.path.join(ROOT, "ceangal", "src", "arabic_data.almd")
    open(dst, "w").write(text)
    print(f"{os.path.relpath(dst, ROOT)}: {len(rows)} ranges")


if __name__ == "__main__":
    main()
