#!/usr/bin/env bash
# The iOS app: the Almide program built by Rust for the device and the
# simulator, wrapped in an Xcode project (generated by XcodeGen) whose app
# target takes the prebuilt executable, the assets, the icon and the privacy
# manifest. Xcode signs, archives and exports.
#
#   tools/package_ios.sh [app] [sim|archive|e2e|all]     (default: playground all)
#   → out/ios/<app>/<Name>.xcodeproj
#     sim:     out/ios/<app>/build/sim/<app>.app       (simulator build)
#     archive: out/ios/<app>/<app>.xcarchive           (device, Release)
#     e2e:     the UI tests (tests/e2e/ios) in a simulator (IOS_SIM, default
#              "iPhone 17"); screenshots and the result in out/ios/<app>/e2e
#
# Signing (from secrets in CI): IOS_TEAM_ID, and an App Store Connect API key
# (ASC_KEY_ID, ASC_ISSUER_ID, the .p8 at
# ~/.appstoreconnect/private_keys/AuthKey_<id>.p8) with which Xcode makes the
# certificate and profile itself; then the archive is signed, exported as
# out/ios/<app>/export/<app>.ipa and validated by App Store Connect. Without
# IOS_TEAM_ID the archive is unsigned — enough to check the bundle, not to
# upload.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
app="${1:-playground}"
what="${2:-all}"
# shellcheck disable=SC1090
source "$root/apps/$app/app.env"
out="$root/out/ios/$app"
mkdir -p "$out"
export PATH="$HOME/.cargo/bin:$PATH" IPHONEOS_DEPLOYMENT_TARGET=16.0 CEANGAL_APP_ID="$APP_ID"

# ── XcodeGen (a pinned release when it is not installed) ──
xcodegen="$(command -v xcodegen || true)"
if [ -z "$xcodegen" ]; then
  xcodegen="$root/out/tools/xcodegen/bin/xcodegen"
  if [ ! -x "$xcodegen" ]; then
    mkdir -p "$root/out/tools"
    curl -fsSL -o "$root/out/tools/xcodegen.zip" https://github.com/yonaskolb/XcodeGen/releases/download/2.46.0/xcodegen.zip
    (cd "$root/out/tools" && rm -rf xcodegen && unzip -q xcodegen.zip)
  fi
fi

# ── the executables, one per SDK ──
build() { # triple → $out/bin/<sdk>/<app>   (IOS_REUSE_BIN=1: keep a built one)
  local triple="$1" sdk="$2" bin="$out/bin/$2/$app"
  [ "${IOS_REUSE_BIN:-0}" = 1 ] && [ -f "$bin" ] && return
  mkdir -p "$out/bin/$sdk"
  if [ "$app" = playground ]; then
    CEANGAL_BUILD_TAG="ios-$sdk" "$root/tools/build_native.sh" -o "$bin" --target "$triple"
  else
    local b="$root/out/build/$app-ios-$sdk"
    rm -rf "$b"; mkdir -p "$b"
    ln -s "$root/apps/$app/src" "$b/src"
    sed -e "s#\"\.\./\.\./#\"$root/#g" "$root/apps/$app/almide.toml" > "$b/almide.toml"
    (cd "$b" && "$root/tools/almide" build src/main.almd --release --target "$triple" -o "$bin")
  fi
}
case "$what" in sim|e2e|all) build aarch64-apple-ios-sim iphonesimulator ;; esac
case "$what" in archive|all) build aarch64-apple-ios iphoneos ;; esac

# ── project sources: assets, icon, privacy manifest, Info.plist ──
proj="$out/project"
rm -rf "$proj"; mkdir -p "$proj/assets" "$proj/Assets.xcassets"
for d in $APP_ASSETS; do cp -Rn "$root/$d/." "$proj/assets/"; done
echo '{"info":{"version":1,"author":"xcode"}}' > "$proj/Assets.xcassets/Contents.json"
icon="$root/store/$app/ios/AppIcon-1024.png"
if [ ! -f "$icon" ] && [ -f "$root/store/$app/icon.env" ]; then
  # the demo apps: their vector mark (store/<app>/icon.env) on its colour,
  # rendered here (the App Store wants no alpha: through JPEG and back)
  # shellcheck disable=SC1090
  source "$root/store/$app/icon.env"
  echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1024\" height=\"1024\" viewBox=\"0 0 108 108\"><rect width=\"108\" height=\"108\" fill=\"$ICON_BG\"/><path d=\"$ICON_PATH\" fill=\"$ICON_FG\"/></svg>" > "$out/icon.svg"
  sips -s format jpeg "$out/icon.svg" --out "$out/icon.jpg" >/dev/null
  sips -s format png "$out/icon.jpg" --out "$out/AppIcon-1024.png" >/dev/null
  icon="$out/AppIcon-1024.png"
fi
if [ -f "$icon" ]; then
  mkdir -p "$proj/Assets.xcassets/AppIcon.appiconset"
  cp "$icon" "$proj/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png"
  cat > "$proj/Assets.xcassets/AppIcon.appiconset/Contents.json" <<'JSON'
{"images":[{"filename":"AppIcon-1024.png","idiom":"universal","platform":"ios","size":"1024x1024"}],"info":{"version":1,"author":"xcode"}}
JSON
fi
privacy="$root/store/$app/ios/PrivacyInfo.xcprivacy"
[ -f "$privacy" ] || privacy="$root/store/playground/ios/PrivacyInfo.xcprivacy"
cp "$privacy" "$proj/PrivacyInfo.xcprivacy"

cat > "$proj/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key><string>\$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleExecutable</key><string>\$(EXECUTABLE_NAME)</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>\$(MARKETING_VERSION)</string>
  <key>CFBundleVersion</key><string>\$(CURRENT_PROJECT_VERSION)</string>
  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
  <key>CFBundleDevelopmentRegion</key><string>en</string>
  <key>CFBundleLocalizations</key><array><string>en</string><string>ja</string></array>
  <key>LSRequiresIPhoneOS</key><true/>
  <key>UILaunchScreen</key><dict/>
  <key>UIRequiredDeviceCapabilities</key><array><string>arm64</string><string>metal</string></array>
  <key>UISupportedInterfaceOrientations</key>
  <array><string>UIInterfaceOrientationPortrait</string><string>UIInterfaceOrientationLandscapeLeft</string><string>UIInterfaceOrientationLandscapeRight</string></array>
  <key>UISupportedInterfaceOrientations~ipad</key>
  <array><string>UIInterfaceOrientationPortrait</string><string>UIInterfaceOrientationPortraitUpsideDown</string><string>UIInterfaceOrientationLandscapeLeft</string><string>UIInterfaceOrientationLandscapeRight</string></array>
  <key>ITSAppUsesNonExemptEncryption</key><false/>
</dict>
</plist>
PLIST
plutil -lint "$proj/Info.plist" >/dev/null

# The app target has no sources: a build phase puts the Rust executable for
# the SDK being built where Xcode expects the binary, then Xcode signs it.
team="${IOS_TEAM_ID:-}"
style=Manual; [ -n "$team" ] && style=Automatic
cat > "$out/project.yml" <<YAML
name: $APP_NAME
options:
  deploymentTarget: { iOS: "16.0" }
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "$VERSION"
    CURRENT_PROJECT_VERSION: "$VERSION_CODE"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_BITCODE: NO
    ARCHS: arm64
    DEVELOPMENT_TEAM: "$team"
    CODE_SIGN_STYLE: $style
targets:
  $app:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: $app
        PRODUCT_BUNDLE_IDENTIFIER: $APP_ID
        INFOPLIST_FILE: project/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: [${app}UITests]
    sources:
      - path: project/Assets.xcassets
      - path: project/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: project/assets
        type: folder
        buildPhase: resources
    postCompileScripts:
      - name: Rust executable
        basedOnDependencyAnalysis: false
        script: |
          set -e
          src="$out/bin/\${PLATFORM_NAME}/$app"
          [ -f "\$src" ] || { echo "error: no executable for \${PLATFORM_NAME} at \$src (run tools/package_ios.sh)"; exit 1; }
          mkdir -p "\${TARGET_BUILD_DIR}/\${EXECUTABLE_FOLDER_PATH}"
          cp "\$src" "\${TARGET_BUILD_DIR}/\${EXECUTABLE_PATH}"
  # the user-level E2E (XCUITest: taps and the on-screen keyboard)
  ${app}UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: $root/tests/e2e/ios
    dependencies:
      - target: $app
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: $APP_ID.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: $app
        SWIFT_VERSION: "5.0"
YAML
(cd "$out" && "$xcodegen" generate --spec project.yml --quiet)
xproj="$out/$APP_NAME.xcodeproj"

if [ "$what" = sim ] || [ "$what" = all ]; then
  xcodebuild -project "$xproj" -scheme "$app" -configuration Release -sdk iphonesimulator \
    -derivedDataPath "$out/dd" CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO build -quiet
  rm -rf "$out/build/sim"; mkdir -p "$out/build/sim"
  cp -R "$out/dd/Build/Products/Release-iphonesimulator/$app.app" "$out/build/sim/"
  echo "built $out/build/sim/$app.app"
fi

if [ "$what" = e2e ]; then
  e2e="$out/e2e"; rm -rf "$e2e"; mkdir -p "$e2e"
  # A simulator of our own, in English with the QWERTY keyboard (the tests
  # type on it), so the user's simulators keep their settings.
  model="${IOS_SIM:-iPhone 17}"
  # an older Xcode: its newest iPhone
  xcrun simctl list devicetypes | grep -q "^$model (" || model="$(xcrun simctl list devicetypes | grep -E '^iPhone [0-9]+ \(' | sed 's/ (.*//' | sort -t' ' -k2 -n | tail -1)"
  sim="ceangal-e2e $model"
  udid="$(xcrun simctl list devices -j | python3 -c "import json,sys; d=json.load(sys.stdin)['devices']; print(next((x['udid'] for v in d.values() for x in v if x['name']==sys.argv[1] and x['isAvailable']), ''))" "$sim")"
  if [ -z "$udid" ]; then
    runtime="$(xcrun simctl list runtimes -j | python3 -c "import json,sys; r=[x for x in json.load(sys.stdin)['runtimes'] if x['platform']=='iOS' and x['isAvailable']]; print(r[-1]['identifier'])")"
    udid="$(xcrun simctl create "$sim" "$model" "$runtime")"
  fi
  xcrun simctl boot "$udid" 2>/dev/null || true
  xcrun simctl bootstatus "$udid" -b >/dev/null
  xcrun simctl spawn "$udid" defaults write -g AppleLanguages -array en-US
  xcrun simctl spawn "$udid" defaults write -g AppleLocale en_US
  xcrun simctl spawn "$udid" defaults write -g AppleKeyboards -array "en_US@sw=QWERTY;hw=Automatic"
  xcrun simctl spawn "$udid" defaults write com.apple.Preferences KeyboardsCurrentAndNext -array "en_US@sw=QWERTY;hw=Automatic"
  # no hardware keyboard: the on-screen one shows, as on a phone (a Simulator
  # app preference, so only on CI machines)
  [ -n "${CI:-}" ] && defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool false
  TEST_RUNNER_E2E_DIR="$e2e" TEST_RUNNER_E2E_APP="$app" xcodebuild -project "$xproj" -scheme "$app" \
    -configuration Release -sdk iphonesimulator -destination "id=$udid" \
    -derivedDataPath "$out/dd" -resultBundlePath "$e2e/result.xcresult" CODE_SIGN_IDENTITY=- CODE_SIGNING_REQUIRED=NO test
fi

if [ "$what" = archive ] || [ "$what" = all ]; then
  sign=(CODE_SIGNING_ALLOWED=NO)
  auth=()
  if [ -n "${ASC_KEY_ID:-}" ]; then
    auth=(-authenticationKeyPath "$HOME/.appstoreconnect/private_keys/AuthKey_$ASC_KEY_ID.p8"
          -authenticationKeyID "$ASC_KEY_ID" -authenticationKeyIssuerID "$ASC_ISSUER_ID")
  fi
  [ -n "$team" ] && sign=(-allowProvisioningUpdates ${auth[@]+"${auth[@]}"})
  rm -rf "$out/$app.xcarchive"
  xcodebuild -project "$xproj" -scheme "$app" -configuration Release -sdk iphoneos \
    -destination 'generic/platform=iOS' -derivedDataPath "$out/dd" \
    -archivePath "$out/$app.xcarchive" "${sign[@]}" archive -quiet
  echo "archived $out/$app.xcarchive"

  # What App Store validation rejects first, checked here (the upload's own
  # validation needs an account: altool below, with secrets).
  a="$out/$app.xcarchive/Products/Applications/$app.app"
  fail() { echo "validate: $*" >&2; exit 1; }
  otool -l "$a/$app" | grep -A3 LC_BUILD_VERSION | grep -q "platform 2" || fail "the executable is not built for iOS devices"
  otool -l "$a/$app" | grep -A4 LC_BUILD_VERSION | grep -q "minos 16.0" || fail "the executable's minimum iOS is not 16.0"
  [ "$(lipo -archs "$a/$app")" = arm64 ] || fail "architectures: $(lipo -archs "$a/$app")"
  for k in CFBundleIdentifier CFBundleShortVersionString CFBundleVersion CFBundleIcons MinimumOSVersion UILaunchScreen ITSAppUsesNonExemptEncryption; do
    plutil -extract "$k" raw -o /dev/null "$a/Info.plist" 2>/dev/null || plutil -extract "$k" xml1 -o /dev/null "$a/Info.plist" || fail "Info.plist has no $k"
  done
  [ -f "$a/Assets.car" ] && ls "$a"/AppIcon60x60@2x.png >/dev/null || fail "no compiled app icon"
  plutil -lint "$a/PrivacyInfo.xcprivacy" >/dev/null || fail "no valid privacy manifest"
  [ -d "$a/assets" ] || fail "no assets"
  # only public system frameworks and libraries
  otool -L "$a/$app" | tail -n +2 | awk '{print $1}' | grep -vE '^/System/Library/Frameworks/|^/usr/lib/' && fail "links something outside the SDK" || true
  echo "validated $a (local checks)"
  if [ -n "$team" ]; then
    cat > "$out/export.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>method</key><string>app-store-connect</string>
  <key>teamID</key><string>$team</string>
  <key>destination</key><string>export</string>
</dict></plist>
PLIST
    xcodebuild -exportArchive -archivePath "$out/$app.xcarchive" -exportPath "$out/export" \
      -exportOptionsPlist "$out/export.plist" -allowProvisioningUpdates ${auth[@]+"${auth[@]}"}
    echo "exported $out/export"
    # App Store Connect's own validation
    if [ -n "${ASC_KEY_ID:-}" ]; then
      xcrun altool --validate-app -f "$out/export/$app.ipa" -t ios --apiKey "$ASC_KEY_ID" --apiIssuer "$ASC_ISSUER_ID"
    fi
  fi
fi
